language: node_js

node_js:
  - "6" # latest version supported by AWS Lambda

install:
  - npm install -g codecov
  - npm install

before_script:
  - cp .env.example .env

script:
  - npm test
  - npm run coverage-codecov
  - codecov

notifications:
  email: false
