service: revuc-slack-stats

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  memorySize: 128

package:
  exclude:
    - .git/**
    - .env
plugins:
  - serverless-dotenv-plugin

functions:
  run:
    handler: index.run
    events:
      - schedule: cron(0 2 * * ? *)
    environment:
      REVUC_API_KEY: ${env:REVUC_API_KEY}
      SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}